name: Backend CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore F&B-ERP-POS-Inventory/F&B-ERP-POS-Inventory.csproj

    - name: Build C# API
      run: dotnet build F&B-ERP-POS-Inventory/F&B-ERP-POS-Inventory.csproj --no-restore -c Release
